### ISSUE TITLE
Easy Announcements on rotation

### ISSUE THREAD

**Issue by DeeJai1** [CatalysmsServerManager/7-days-to-die-server-manager#1109]
**Is your feature request related to a problem? Please describe.**
Cronjobs are fine, however setting up timed announcements when you want multiple single announcements can be problematic using that system

**Describe the solution you'd like**
GUI on the webpage, to add single messages, which get added to a list. Ability to add custom timer to this, so that when timer pops, one of the messages in the list will be displayed to the server

**Describe alternatives you've considered**
We are experimenting with cronjobs currently, however this can be time consuming and very difficult for those without any knowledge of this system

**Additional context**
This is available on another server manager, so this is not my idea in the slightest, I just like things to be easy.

**Comment by niekcandaele** [comment]
Is it just a random message from the list? Why not use the `randList` helper for this?

**Comment by niekcandaele** [comment]
Continued on Discord, closing this issue.

For any wandering Googlers: https://discordapp.com/channels/336821518250147850/427106880255426560/941770358359478413

**Comment by trevorjd** [comment]
Hi folks, for later visitors, here's the solution we came up with. This script will iterate through a list of announcements, then start again from the top of the list. 

1. Set the maxAnn variable to the number of announcements you have. The counter will reset once it exceeds this number.
2. Add as many announcement lines as you like, make sure that you name the variable correctly (Ann1, Ann2, etc.)
3. Change "botname" on the last line to change the appearance in-game.
4. Paste it into CSMM Server Automation and set your cron values as desired.
5. Click Submit!

    {{setVar "counter" (add (getVar "counter") 1)}};
    {{setVar "maxAnn" 3}}; 
    {{setVar "Ann1" "[89d1d6] Announcement 1 text"}};
    {{setVar "Ann2" "[89d1d6] Announcement 2 text"}};
    {{setVar "Ann3" "[89d1d6] Announcement 3 text"}};
    {{#if (gte (getVar "counter") (getVar "maxAnn"))}}  {{setVar "counter" 1}} {{/if}};
    say2 botname "{{getVar (add "Ann" (getVar "counter"))}}";
