### ISSUE TITLE
Randomisation for region resets

### ISSUE THREAD

**Issue by trevorjd** [CatalysmsServerManager/7-days-to-die-server-manager#1123]
**Is your feature request related to a problem? Please describe.**
I feel that mudflation is a concern with region resets, as is 'reset camping". My takeaway from reading the Reset Regions documentation is that all flagged regions are reset at once. Greater delay between reboots helps address the mudflation issue but players whose schedules coincide with the scheduled reset will always get pick of the best loot areas.

**Describe the solution you'd like**
It would be nice to use a command like `cpm-shutdownba 10 reset 5` (or resetunclaimed) that we can run on a daily basis that randomly chooses 5 of our regions (from the total pool of flagged regions) for a reset. Adjusting that number allows administrators to adjust the mudflation level and having them randomly selected should help share the loot around.

**Describe alternatives you've considered**
None. My idea is perfect! :)

**Additional context**
n/a

**Comment by Prisma501** [comment]
CPM is not under active development anymore. It will get updates to be future gameversion compatible and bugfixes (if i find the bug big enough). Feature requests are not an option.

**Comment by trevorjd** [comment]
Understood. Thanks for the quick reply!
