### ISSUE TITLE
Persistant variables sort, lock and search

### ISSUE THREAD

**Issue by 200779b** [CatalysmsServerManager/7-days-to-die-server-manager#1135]
When I wipe, lots of variables need to be deleted, but some must remain. A way to prevent some of the variables to be affected by the "select all check box" and/or by the delete button would be great. Even more if locked becomes an optional argument for setVar. 

Also a way to sort the variables in the variable tab by name and date could be useful.

Finally, a searchVar ("text") that could return an array of all variables that contain (or at least start with) "text" and its value would be awesome to, for instance, make a contest such as top zombie killer player of the week.

**Comment by Expostech** [comment]
The requested features have been added in the latest release: [v2.1.0](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/releases/tag/v2.1.0).

The ``setVar`` helper now has an optional argument that sets the lock state of a variable.

The ``listVar`` helper returns an array of all the variables that match the search query.

Search Query Options:
- Contains: ``"*test*"`` or ``"test"``
- Starts With: ``"test*"``
- Ends With: ``"*test"``
- Return All: ``"*"`` or ``""``

Search Query Only:
```
listVar <search query>
```
```
{{#each (listVar "test")}}
{{{this.createdAt}}} - {{{this.updatedAt}}} - {{{this.name}}} - {{{this.value}}} - {{{this.server}}} - {{{this.preventDeletion}}}
{{/each}}
```

Search Query + Limit:
```
listVar <search query> <limit>
```
```
{{#each (listVar "test" 4)}}
{{{this.createdAt}}} - {{{this.updatedAt}}} - {{{this.name}}} - {{{this.value}}} - {{{this.server}}} - {{{this.preventDeletion}}}
{{/each}}
```

Search Query + Sort:
```
listVar <search query> <column to sort by> <sort direction>
```
```
{{#each (listVar "test" "name" "asc")}}
{{{this.createdAt}}} - {{{this.updatedAt}}} - {{{this.name}}} - {{{this.value}}} - {{{this.server}}} - {{{this.preventDeletion}}}
{{/each}}
```

Search Query + Sort + Limit:
```
listVar <search query> <column to sort by> <sort direction> <limit>
```
```
{{#each (listVar "test" "name" "desc" 4)}}
{{{this.createdAt}}} - {{{this.updatedAt}}} - {{{this.name}}} - {{{this.value}}} - {{{this.server}}} - {{{this.preventDeletion}}}
{{/each}}
```

**Comment by niekcandaele** [comment]
Docs added too: https://github.com/CatalysmsServerManager/docs/pull/414

Good work @Expostech !
