### ISSUE TITLE
Home teleport

### ISSUE THREAD

**Issue by davslo** [CatalysmsServerManager/7-days-to-die-server-manager#117]
**Is your feature request related to a problem? Please describe.**
Lack of home teleport without cpm.

**Describe the solution you'd like**
A simple ability for players to be able to have /sethome and /home using csmm.

**Describe alternatives you've considered**
Thought about just using /tele but people like the simple /home teleport with no extra text after it to get home quickly.

**Additional context**
I personally think it would help make csmm a great stand-alone server manager.

**Comment by davslo** [comment]
basically the ability to store a location similar to /settele <name>, only it’s a simple /sethome.

And instead of using /tele <name> to visit the stores location it would simply be /home.

**Comment by niekcandaele** [comment]
What about using the `teleportplayerhome` in a custom command @davslo ? I think that should fit your usecase, right?

**Comment by niekcandaele** [comment]
Confirmed in Discord this fills the feature request
