### ISSUE TITLE
Random() custom function

### ISSUE THREAD

**Issue by Banthors** [CatalysmsServerManager/7-days-to-die-server-manager#118]
This is a very simple request. I would like to be able to call a command that allows a person to be randomly spawned in the map. If you want to go advanced could set boundaries for where to not teleport.

**Comment by niekcandaele** [comment]
I would implement this as a `random()` function to be used in custom commands, hooks, etc. This will allow the use case to be filled and can also be reused for many other purposes

**Comment by halkeye** [comment]
me me me me, i want to do it

**Comment by Banthors** [comment]
Thank you guys. This is awesome and will work perfectly for what I'm trying to do on my server. Will it be like random(x,y) and can pass that into the teleport coords

**Comment by niekcandaele** [comment]
The actual command could look something like 

`teleportplayer ${player.steamId} random(500,2000) -1 random(500,2000)`

Which you can just drop into a custom command or a hook, however you want to use it.

We'll see how @halkeye implements it ofcourse ^^

**Comment by niekcandaele** [comment]
Perhaps keeps track of a random number is a good idea, so the same number can be reused later. Consider this simple example:

`addCurrency(${player.id}, random(5,10)); say "${player.name} just got random(5,10) coins!"`

**Comment by halkeye** [comment]
Yea but that also means that you can't have 2 random numbers in a command, so random teleports or anything else won't work.

**Comment by Banthors** [comment]
Yeah the whole point of random is to allow truly random teleports. If a person likes their teleport they can save it with /settele (Name). My goal in asking for it was to make a pvp server with a central lobby/spawn with rules and info than to leave they have to randomly tp out into the world. So the chances of running into someone right after tping is slim to none.

**Comment by niekcandaele** [comment]
Yeah my example didn't account for it. I think the possibility of reusing the same value later in the command can be very useful. But then we kind of start getting into variables and that might be out of scope for this request

**Comment by Banthors** [comment]
Was it added?

**Comment by niekcandaele** [comment]
Yep will be in V1.14.2!
