### ISSUE TITLE
Request: Add EOS ID to the player object in the built in variables for custom commands

### ISSUE THREAD

**Issue by mixels** [CatalysmsServerManager/7-days-to-die-server-manager#1187]
**Is your feature request related to a problem? Please describe.**
Now that 7 Days is moving toward a cross platform implementation, Steam ID will no longer be a reliable way to identify a player. EOS ID is wholly supplanting it for cross-platform support. I would like to be able to write custom commands that 100% reliably will operate on the correct player. To do that, I now need access to EOS ID, and dependence on EOS ID will grow as FunPimp deprecates the Steam ID identifier.

**Describe the solution you'd like**
I would like access to an eosId property on the data.player object and on the data.server.onlinePlayers[] collection objects.

**Describe alternatives you've considered**
Entity ID is potentially useful as an identifier, but it's unclear whether a player's entity ID will ever change or whether it will ever be possible for an entity ID value to be used for one entity and then later, for whatever reasons, reused by a different entity.

**Additional context**
None. :)

Thank you for considering this request!

**Comment by niekcandaele** [comment]
This was already implemented in https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/1176 
But no new version release for it yet.. :)
