### ISSUE TITLE
Suggestion: Add 'tp' aliases to the ingame teleport commands for consistency

### ISSUE THREAD

**Issue by mixels** [CatalysmsServerManager/7-days-to-die-server-manager#1191]
**Is your feature request related to a problem? Please describe.**
Not much of a problem. Just a bit of inconsistency with regard to one of the more useful aliases for the in-game teleport command `tp`.

**Describe the solution you'd like**
The ingame teleport command has an alias 'tp'. It's nice and short, and it's similar to other server tools mods that use `wp` for waypoints. Great. But then the commands to set teleports and configure teleports as public or private do not have similarly named aliases. I would like to see aliases added such as `tpset`, `tppublic`, and `tpprivate` for consistency.

That's all. :)

**Comment by 200779b** [comment]
You can add those as custom commands with a required argument

**Comment by niekcandaele** [comment]
Happy to take suggestions for more command aliases :) 

CSMM has a pretty well defined system for adding command aliases, [here's an example](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/worker/processors/sdtdCommands/commands/setTele.js#L10)

**Comment by niekcandaele** [comment]
Fixed with https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/1322
