### ISSUE TITLE
Add test for setting lastSuccess after log collection

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#127]
Followup to https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/126

**Comment by niekcandaele** [comment]
Oh @halkeye you already added this in a different commit :smile: 

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/6f49ad828047858349318a08236ce7532979bda6/test/unit/hooks/sdtdlogs/LoggingObject.test.js#L255-L269

**Comment by halkeye** [comment]
yay go me
