### ISSUE TITLE
Increase the {times} directive to allow more than 100 iterations

### ISSUE THREAD

**Issue by trevorjd** [CatalysmsServerManager/7-days-to-die-server-manager#1358]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At the moment, the (#times) directive is limited to 100 iterations. I'd like some more, please. Even 10-15 more would be enough!

**Describe alternatives you've considered**
It's quite possible my code could be more efficient but I'm not a programmer :)

**Additional context**
With each new playthrough, we flag most regions that contain city blocks or important POIs. Resetting all at once will result in mudflation, so I've created a method to just reset a subset of the full list. I have one persistent var for each region filename. The first script chooses 5 at random. We then reboot and at server start, the second script reflags everything.

With a large map 8k+ it's not difficult to want to flag more than 100 regions as CPM reset regions. My scripts as written use {#times} which caps me at 100 regions.

{{! Randomise Regions for Reset }} mrr remove -5120 5120 5120 -5120; {{#times 5}} mrr add {{itemAt (arrayify (split (getVar (add "masterRegionList" (randNum 1 101))))) this}}; {{/times}}

{{! Restore Master List }} {{! Ensure the #times value is at least 1 more than your number of regions }} mrr remove -5120 5120 5120 -5120; {{#times 100}} {{#each (arrayify (split (getVar (add "masterRegionList" index))))}}; mrr add {{this}}; {{/each}}; {{/times}}

**Comment by niekcandaele** [comment]
Raised the limit to 250, will land on the master branch soon :)
