### ISSUE TITLE
Unable to add admin through Bot (Player profile screen)

### ISSUE THREAD

**Issue by TheBaptizer** [CatalysmsServerManager/7-days-to-die-server-manager#151]
**Describe the bug**
Getting a forbidden error when trying to add an existing moderator to an admin role through the player profile screen. Have set admin role to level 0 and allowed player to have level 0 on the serveradmin.xml.  

**To Reproduce**
1. Go to 'players profile screen'
2. Click on 'roles, select Admin, click on set'
3. See error 'Forbidden'

**Expected behavior**
This should have set the player to admin role.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by niekcandaele** [comment]
I think the cause will lay here:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/controllers/role/add-player.js#L49
If the users current role level is the same as the one he is setting, it will return forbidden. Not 100%, should test to make sure that this is indeed the cause :)
