### ISSUE TITLE
I'm stuck but nothing happens or we need a server game first, we're new to this game.

### ISSUE THREAD

**Issue by GmaerSkill** [CatalysmsServerManager/7-days-to-die-server-manager#1535]
I'm still not sure if this is a bot or a server helper and we need to have a server game first to be able to install this.

**Comment by niekcandaele** [comment]
Hello, CSMM doesn't run 7d2d servers, it connects to an already running server. So yes, you will need to have a game server first before you can use CSMM.

Sorry for the late response. For questions like this, [Discord](https://catalysm.net/discord) is a better channel. We'll be able to help you and answer questions much faster there. 

I'll close this issue for now as it isn't a bug in CSMM.
