### ISSUE TITLE
Whitelist Country Ban option

### ISSUE THREAD

**Issue by m4tm4t** [CatalysmsServerManager/7-days-to-die-server-manager#169]
**Is your feature request related to a problem? Please describe.**
I want to ban all countries except one or two and the blacklist will took too many time one by one

**Describe the solution you'd like**
A whitelist option for allowed countries

Thank you :)

**Comment by niekcandaele** [comment]
Implementation proposal:

- Add a new attribute to SdtdConfig in the database, create a migration for this. I think a boolean 'whitelist' should do

- Add an API controller to update this value
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/tree/master/api/controllers/SdtdServer/countryBan

- Update the logic in the country ban hook
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/countryBan/index.js#L430

**Comment by LethalLeonard** [comment]
I'll get this one done
