### ISSUE TITLE
Discord: Modification to Text Chat in Game.

### ISSUE THREAD

**Issue by digital-play** [CatalysmsServerManager/7-days-to-die-server-manager#211]
Hi Cataclysm,

Can I please request the following changes to the discord integration into 7DTD?

1. Change the output of discord chat which is relayed to the in game chat to instead of saying SERVER: 
it says the discord channel name instead? 

2. An option to change the colour of the text which is relayed into game as by default it is just white.

Thanks
SnowWhite

**Comment by niekcandaele** [comment]
Good request, but please follow the issue template. I'll close this, please remake the issue or edit this one (and ping me)
