### ISSUE TITLE
Shop - Categories

### ISSUE THREAD

**Issue by MADMAN72** [CatalysmsServerManager/7-days-to-die-server-manager#221]
It is difficult to quickly find an item you are looking for if you have a large shop.

Could we create a way to organize the shop better by allowing it to be broken down into categories?  Examples: Food, Drinks, Decor, Vehicles, etc.

Thanks!

**Comment by niekcandaele** [comment]
Good suggestion, duplicate of https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/59 though :smile:
