### ISSUE TITLE
docker-compose port binding conflict

### ISSUE THREAD

**Issue by m4tm4t** [CatalysmsServerManager/7-days-to-die-server-manager#236]
**Describe the bug**
The web and worker services are binding the same port that raise a `Bind for 127.0.0.1:30005 failed: port is already allocated` when running `docker-compose up`

**Desktop (please complete the following information if this is a problem on the CSMM web application):**
 - OS: Archlinux / Docker

Removing the port binding on worker service fix the issue

**Comment by niekcandaele** [comment]
This line then?
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/docker-compose.yml#L37

I don't think the worker needs a port, right @halkeye ?

**Comment by m4tm4t** [comment]
Yes it's this line :+1:

**Comment by halkeye** [comment]
Yea worker doesn't need port
