### ISSUE TITLE
Day/Time Set Option

### ISSUE THREAD

**Issue by ayz1e** [CatalysmsServerManager/7-days-to-die-server-manager#271]
A GUI option to set the Day/Time on the server dashboard.

Server stats show the server time on the dashboard, but it would be nice to have a clock displayed, where you can click the clock and adjust the day/time and apply it to the server.

**Comment by niekcandaele** [comment]
Displaying time can definitely be done, however changing it is a very different story. The `settime` command is very, very glitchy. It could mess up hordenights, loot resets, ...
