### ISSUE TITLE
Cron module does not send notifications

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#297]
Likely because the jobs get executed in the worker and don't have access to the required helper(s)?

**Comment by halkeye** [comment]
Well they don't have full access to the discord websocket. It'll need to use the api not the websocket.

**Comment by niekcandaele** [comment]
Yeah exactly

Made a last minute change to move cron hook execution into the worker and did not consider notifications :smiley:

**Comment by niekcandaele** [comment]
Makes me think, probably a good idea to make a sort of Discord REST client or something to handle this
