### ISSUE TITLE
Refactor notifications to use Discord webhooks

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#299]
Instead of using the bot client to sends messages, we should use [webhooks](https://discordjs.guide/popular-topics/webhooks.html).

Looks like we'll need to store the webhook ID and token in the database so blocked by migrations (#198) for now.

**Comment by halkeye** [comment]
The webhook is only if you don't want a bot in there. The bot can write directly. I'll see if I can dig up my old branch

**Comment by niekcandaele** [comment]
You want to use the bot client for this? I think that will fail if the bot is in many guilds, it has to start sharding at a certain point. If a notification has to be sent to a guild that is not active in the current shard, it'll fail.

I believe that's how it works anyway, if you can get around that please share :smiley:
