### ISSUE TITLE
Make Discord bot owners configurable via env variables

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#314]
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/63dfc17d0663e5695b7f608b6698769ae53340db/config/custom.js#L31

Currently this is hardcoded, should be controlled by an env variable. Default to no owner in env var is undefined. Read from `process.env`

**Comment by Andreybest** [comment]
Hello! I can try doing this one. Can you assign me?

**Comment by niekcandaele** [comment]
Sure thing! Feel free to pop into Discord if you need any help getting started :smile:
