### ISSUE TITLE
chatChannelRichMessages is only taken into account when starting up the discord bot

### ISSUE THREAD

**Issue by halkeye** [CatalysmsServerManager/7-days-to-die-server-manager#320]
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/discordChatBridge/chatBridgeChannel.js#L51-L70

When a user changes the value, the hooks are already started so doesn't get the new value.

**Comment by niekcandaele** [comment]
Weird, the controller should restart the chatbridge and apply any config changes

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/controllers/SdtdServer/discordBot/set-chat-channel.js

**Comment by halkeye** [comment]
Is that controller mislabeled or only run when you click the set channel button

**Comment by niekcandaele** [comment]
The settings are only applied when you click the set channel button yeah. Better name for it would be 'set-chatBridge-config' or something

**Comment by niekcandaele** [comment]
This can be closed I think, user confirmed on Discord it's working after they clicked the save settings button
