### ISSUE TITLE
Items in spaces are not supported by the player give item controller

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#324]
Issue is here:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/controllers/Player/give-item.js#L59

If an itemName has spaces in it, the command syntax fails.

The same issue but for shop was fixed in this PR:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/294

**Comment by niekcandaele** [comment]
There's a test for this controller but it completely misses this case
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/test/integration/controllers/give-item.test.js

**Comment by jcardoz** [comment]
@niekcandaele  - i can take a look at this one - seems to be a simple fix
I will try and update the test case as well

**Comment by niekcandaele** [comment]
Perfect!

**Comment by jcardoz** [comment]
@niekcandaele  - please take a look at:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/378

I think the test case will now cover this scenario as well
