### ISSUE TITLE
Discord command status should take custom bloodmoon settings into account

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#327]
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/discordBot/commands/sdtd/status.js#L57

Hardcoded to 7 days atm. I think this data can be retrieved via the `gg` sdtd command.

**Comment by Prisma501** [comment]
gg indeed:
GamePref.BloodMoonFrequency = X

**Comment by Prisma501** [comment]
But better would be ggs. It lists the actual next bloodmoon day:
GameStat.BloodMoonDay = 140

No need to calculate yourself AND it takes the other relevant setting GamePref.BloodMoonRange into account (random bloodmoons)

**Comment by niekcandaele** [comment]
Beautiful! Thanks
