### ISSUE TITLE
hooks export / import / delete all

### ISSUE THREAD

**Issue by PauloAlmas** [CatalysmsServerManager/7-days-to-die-server-manager#341]
hooks 

why there is no Export csv , import csv, select all / delete all ?

ingame commands have that function, why not this have ?

**Comment by niekcandaele** [comment]
There are already issues for this, which is what I linked you on Discord.
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22Import%2FExport+rework%22
