### ISSUE TITLE
Fix validation for top command

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#349]
Reported via Discord:

![image](https://user-images.githubusercontent.com/22315101/95640769-ab4d1c00-0a9e-11eb-9588-42e16d80e858.png)
![image](https://user-images.githubusercontent.com/22315101/95640771-b1db9380-0a9e-11eb-9b89-863e05aaa624.png)

Command worked when `+top deaths` was used.

Capitalization is the issue, there's already some validation but that's not working 100% 😄 .
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/discordBot/commands/sdtd/top.js#L16

For UX, it's probably best to use `.toLowercase()` on the arg

**Comment by adhammo** [comment]
Hello @niekcandaele,

After investigating the **discord.js-commando** docs and source code, I found that **oneOf** is not used for validation inside the argument (I think it is just used for indicating the different valid values).

I also found that there was a validate method that takes an argument value and its information and returns a bool if it is valid, and if an error occurred it will output a predefined message (resides in error property inside argument value class).

Can you assign me this issue, please?

**Comment by halkeye** [comment]
Assigned

**Comment by adhammo** [comment]
Hey @halkeye,
Please, check out the PR.
