### ISSUE TITLE
Add dev server invite link to Discord bot

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#350]
Current message is a bit misleading, we don't want people PMing devs but rather asking on the dev server

![image](https://user-images.githubusercontent.com/22315101/95641033-3f6bb300-0aa0-11eb-9f81-51da3f0e308a.png)

So add invite to https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/discordBot/index.js#L30-L31

Can use `https://catalysm.net/discord` as invite link

**Comment by niekcandaele** [comment]
See also:
https://discord.js.org/#/docs/commando/master/class/CommandoClient

**Comment by halkeye** [comment]
I think it should be a process.env so we don't get bugged for self installs?

**Comment by niekcandaele** [comment]
Yeah good point, this should indeed be an env variable :smile:

**Comment by Menuka5** [comment]
@niekcandaele Hi I came here from hackoberfest. Is this assigned to anyone? I would like to help with this :D

**Comment by niekcandaele** [comment]
All yours! I've assigned it to you :)

**Comment by Menuka5** [comment]
@niekcandaele Thank you :D

**Comment by jcardoz** [comment]
@Menuka5 - Are you working on this one - if not - I can work on this

**Comment by halkeye** [comment]
@jcardoz go ahead, we have a lot of newbie friendly tickets, so if @Menuka5 comes back, they can take one of the other ones

**Comment by jcardoz** [comment]
@halkeye thanks
I have raised a PR for the same https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/377

**Comment by jcardoz** [comment]
thanks @halkeye  @niekcandaele
