### ISSUE TITLE
DepricationWarning

### ISSUE THREAD

**Issue by ich777** [CatalysmsServerManager/7-days-to-die-server-manager#38]
Got the follwing error message since the last update from nodejs:

[DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

I'm running nodejs v10.17.0 on Ubuntu 18.04

**Comment by niekcandaele** [comment]
Hello

This is caused by https://www.npmjs.com/package/sails-mysql which is still using an older version of the mysql package. Not much I can do I'm afraid except hope that they update.

PS: Thanks for your work on the unraid Docker image :smiley:

**Comment by ich777** [comment]
@niekcandaele Thank you for the response.
Ok thanks, but any way i can get around it? The Unraid container is now broken... :(

**Comment by niekcandaele** [comment]
This shouldn't be an issue yet. Deprecation warning means that it will stop working in the future but it's still OK for now. Do you see any other errors happening?

**Comment by ich777** [comment]
@niekcandaele No other errors, i've rebuilt the images yesterday and now this error shows up and the container doesn't start successfully.

**Comment by niekcandaele** [comment]
Still using the same database? An update was released a while ago that needed some queries to be executed
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/releases/tag/v1.11.1

If you don't have those DB changes, I imagine CSMM wont start properly

**Comment by ich777** [comment]
@niekcandaele Okay thank you i will look into that in a few days and report back (got not much spare time at the moment)...

**Comment by ich777** [comment]
@niekcandaele Btw, no not using the same database, a new installation of the Docker, also wich nodejs version is officially supported? I tried using 10.x and 12.x

**Comment by niekcandaele** [comment]
Currently I am using 10.x in my production instances. If you initialize a new database, the migrations shouldn't be necessary as they are included in the start up then.

When you get a chance, can you post a full log btw?

**Comment by ich777** [comment]
Oh nice i've now got it, the container starts fine in a new instance with the warning but not on the old.
One information for the docker, can i run these commands on older instances also so that i can build it as a fixed startup command in my container?

**Comment by niekcandaele** [comment]
If you spin up new containers, CSMM will automatically create the tables. However, if a database already exists CSMM will not touch it to prevent dataloss. So that means you only need to run these commands for containers where a database already exists. This'll only be necessary if you are updating, I will always post the required SQL to execute in the release notes. I'm not sure how to best approach this in your docker image but I hope this info helps you?
