### ISSUE TITLE
Index page not loading properly

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#380]
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/views/index.ejs#L156
:smile: 

That causes the page to completely error out. After deleting that line, the page loads but the sidenav etc get loaded on the index page. The index page should use a different layout than the rest of the application. 

![image](https://user-images.githubusercontent.com/22315101/95970957-d9b95700-0e10-11eb-950d-a5e480815ce2.png)

See https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/config/routes.js#L28

**Comment by halkeye** [comment]
That line should be deleted. It was testing async locals and I forgot to remove it.
