### ISSUE TITLE
Table for command edit isn't working. (╯°□°）╯︵ ┻━┻

### ISSUE THREAD

**Issue by SylenThunder** [CatalysmsServerManager/7-days-to-die-server-manager#388]
**Describe the bug**
Table for editing commands is muffed up.

**To Reproduce**
1. Go to 'server'
2. Click on 'Settings'
3. Scroll down to 'Custom Commands'

**Expected behavior**
Table should have edit buttons on the right column, and not across the bottom.

**Screenshots**
https://i.gyazo.com/67b4e0c0ecace51bbc37dc5a2bab1800.png

**Desktop (please complete the following information if this is a problem on the CSMM web application):**
 - OS: Win 10
 - Browser Chrome and Brave

**7 days to die server info:**
 - Output of the `version` command:
N/A

**Additional context**

**Comment by melsaa** [comment]
Hi, I'd like to work on this issue.

**Comment by niekcandaele** [comment]
Awesome!

The problem is somewhere here:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/views/sdtdServer/partials/settings/commandSettings.sejs#L149


I've assigned this issue to you :)
