### ISSUE TITLE
Add CONTRIBUTE.md

### ISSUE THREAD

**Issue by pranavpatel3012** [CatalysmsServerManager/7-days-to-die-server-manager#395]
In the spirit of getting more contributors for the project in the Hacktoberfest, the above documents would be appreciated and will be a good guide for new comers to open source.

**Comment by pranavpatel3012** [comment]
Hi, I'd would like to add this file. Can I please be assigned to do this work ?

**Comment by niekcandaele** [comment]
Sure, I think a file like this will at least need

- Welcome/intro
- Links to all contact avenues
- (Opinionated) way to set up a dev environment (Compose file will help with this)
- How to run tests 
- Some info on how people can pick an issue to work on (label 'good first issue')
- Mention the code of conduct

Those are some basic things I can think of right now. If you google contributing.md guides you'll likely find some good examples
