### ISSUE TITLE
Error when attempting to start self-hosted server (exit code 137)

### ISSUE THREAD

**Issue by Connor-Knabe** [CatalysmsServerManager/7-days-to-die-server-manager#398]
**Describe the bug**
I get a failure when running npm run start with exit code 137

**To Reproduce**
1. follow self host guide to setup everything correctly
2. run db migration
3. run NODE_ENV=production npm run start
4. see error

**Expected behavior**
For the application to start as normal

**Error log**
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node',
> 1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'start:worker' ]
> 2 info using npm@6.14.6
> 3 info using node@v10.22.1
> 4 verbose run-script [ 'prestart:worker', 'start:worker', 'poststart:worker' ]
> 5 info lifecycle csmm@1.17.5 prestart:worker: csmm@1.17.5
> 6 info lifecycle csmm@1.17.5 start:worker: csmm@1.17.5
> 7 verbose lifecycle csmm@1.17.5 start:worker: unsafe-perm in lifecycle true
> 8 verbose lifecycle csmm@1.17.5 start:worker: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/csmm/7-days-to-die-server-manager/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/csmm/7-days-to-die-server-manager/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle csmm@1.17.5 start:worker: CWD: /home/csmm/7-days-to-die-server-manager
> 10 silly lifecycle csmm@1.17.5 start:worker: Args: [ '-c', 'node worker.js' ]
> 11 silly lifecycle csmm@1.17.5 start:worker: Returned: code: 137  signal: null
> 12 info lifecycle csmm@1.17.5 start:worker: Failed to exec start:worker script
> 13 verbose stack Error: csmm@1.17.5 start:worker: `node worker.js`
> 13 verbose stack Exit status 137
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid csmm@1.17.5
> 15 verbose cwd /home/csmm/7-days-to-die-server-manager
> 16 verbose Linux 5.4.0-45-generic
> 17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "start:worker"
> 18 verbose node v10.22.1
> 19 verbose npm  v6.14.6
> 20 error code ELIFECYCLE
> 21 error errno 137
> 22 error csmm@1.17.5 start:worker: `node worker.js`
> 22 error Exit status 137
> 23 error Failed at the csmm@1.17.5 start:worker script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 137, true ]

Any help would be much appreciated, thanks!

**Comment by niekcandaele** [comment]
Could you try adding

`sails.log.error(err)`
before the process.exit call?
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/c57ce934d923103cda00db803152b40618b106ea/worker.js#L40-L43

I think the error message is getting swallowed there

**Comment by Connor-Knabe** [comment]
Figured it out! 

I was running this on a 1GB RAM server but looks like 2GB is required

**Comment by Connor-Knabe** [comment]
@niekcandaele also FWIW I added that sails.log but it seems to be failing before that call happens (the log never printed)

I added a log above and it seemed to print but not when it got into the sails.load function 
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/c57ce934d923103cda00db803152b40618b106ea/worker.js#L40

Any suggestions on how to capture that for others who may experience similar issues?

I did add a note to the install docs about 2GB RAM so hopefully no one else will encounter this

**Comment by niekcandaele** [comment]
Not really any suggestions for that. It's been bugging me for a while, makes debugging self-hosting issues significantly harder. I think the problem might be with the `run-p` command we use in start... 

Thanks for being thorough!
