### ISSUE TITLE
Will deal with this issue

### ISSUE THREAD

**Issue by Mykiiii** [CatalysmsServerManager/7-days-to-die-server-manager#403]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if this is a problem on the CSMM web application):**

**7 days to die server info:**
 - Output of the `version` command:

**Additional context**

**Comment by niekcandaele** [comment]
Hi @Mykiiii It looks like you forgot to fill in the issue template, can you do that please?

**Comment by niekcandaele** [comment]
Judging from the title, I think you may have meant to comment on an issue instead of creating a new one.

I'll close this issue, but if you do want to report a bug you can create a new one. Or edit this one and give me a ping so I can reopen!
