### ISSUE TITLE
Add logging for failures when giving an item via the claim command

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#412]
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/f432862f62cde779880c0892b5ec797bb3510e2e/api/hooks/sdtdCommands/commands/claim.js#L67-L69

A user had an issue with this and it was hard to debug because the actual command output is suppressed. We should add a call to `sails.log` so that it can be traced

**Comment by cardinalion** [comment]
Can I take this?

**Comment by halkeye** [comment]
Yes please

**Comment by halkeye** [comment]
Please reach out here or discord if you run into trouble

**Comment by cardinalion** [comment]
What would be a good log message for this error?

**Comment by halkeye** [comment]
The actual message doesn't matter too much. Usually we include the function name, but needs to at least record the response.
