### ISSUE TITLE
Who feature has broken string for radius

### ISSUE THREAD

**Issue by SylenThunder** [CatalysmsServerManager/7-days-to-die-server-manager#423]
**Describe the bug**
Who feature has broken string for radius

**To Reproduce**
1. Go to 'server'
2. Click on 'T' to open in-game chat
3. Type '/who'

**Expected behavior**
Radius should return the value of the requested size, and not the hook value. (wrong worg. can't think of right word. not enough coffee.... the thing that is looking for the input.  Can see in screenshot.)

**Screenshots**
https://cdn.discordapp.com/attachments/358371721482338314/768491898419413002/unknown.png

**Desktop (please complete the following information if this is a problem on the CSMM web application):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)

**7 days to die server info:**
 - Output of the `version` command:
Game version: Alpha 19.2 (b4) Compatibility Version: Alpha 19.2
Mod CSMM Patrons: 17.7
Mod Allocs command extensions (Patty edit for A19 b109): 20.2
Mod Allocs server fixes  (Patty edit for A19 b109): 23.2
Mod Allocs MapRendering and Webinterface (Patty edit for A19 b109): 33.2
Mod HealMe Buff: 1.5
Mod Khaine's 3-slot Forge Input: 1.0.0
Mod Khaine's 60-slot Bigger Backpack Mod: 1.0.0
Mod Less Trees: 1.0
Mod Ragnarok-Screen-Mods: 1.0
Mod RELXIX_UI_CompassStats: 1.0.3
Mod SylenThunder_Door_Hax_Fix: 0.0
Mod BP_Info: 19.0.180

**Additional context**

**Comment by niekcandaele** [comment]
You can try changing the veriable inside the reply types.

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/sdtdCommands/commands/who.js#L68

I see the functions returns `radius` instead of `size`.


I think the default reply for this should be adjusted though
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/033a72c647474b049670e99e619a2b87cd1b2dde/api/hooks/sdtdCommands/replyTypes.js#L316-L321

**Comment by SylenThunder** [comment]
/who is just a button I tick in the settings.  I don't have control over the variable.

**Comment by niekcandaele** [comment]
See custom command replies on the settings page :). It lets you customize pretty much all the command responses
![image](https://user-images.githubusercontent.com/22315101/96904895-00723000-1498-11eb-806c-acb40fd9b19a.png)

**Comment by SylenThunder** [comment]
oh really?   learn something new every day.
