### ISSUE TITLE
KillEarner should collect all the promises then await on all of them.

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#429]
should collect all the promises then await on all of them.

_Originally posted by @halkeye in https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/416#r509786160_

----

Awaiting each promise separately is slower than running them in parallel.

**Comment by julesnuggy** [comment]
Hi there - interested in working on this issue. Any more detail on *which* promises to parallelise? There are quite a few! XD

**Comment by julesnuggy** [comment]
If the answer is "all of them", are there any particular modules / features which need them the most at the moment?

**Comment by niekcandaele** [comment]
Hehe should've been more clear :smile: 

We're talking about this loop here. It does a bunch of `await` calls that shouldn't be sequential but can be parrallel. Same thing for the loop a few lines down

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/fa59b0e728b9016bcfffc133a0c81da37d1df023/worker/processors/kill/index.js#L16-L23

**Comment by julesnuggy** [comment]
Cool, thanks for the direction :-) 
Change my comment after I re-read the title of the issue and panicked that I'd sound stupid 😅 But this is helpful as I then realised there are number files/classes referring to KillEarner XD

**Comment by niekcandaele** [comment]
No worries, it's hard to find what we want to change when I don't properly explain in the issue :smile: I'll assign this to you, if you need any help/guidance feel free to hop into Discord!
