### ISSUE TITLE
Allow full player export to Clipboard/Excel/PDF, or allow table row count to be increased

### ISSUE THREAD

**Issue by saminal1** [CatalysmsServerManager/7-days-to-die-server-manager#434]
In order to compare players stats in depth (e.g. to settle friendly disputes about who's KDR is better) it's useful to export the player list to Excel. However, the export functions only export the visible rows on the page.

Two possible solutions would be
1) Add an 'export all' tickbox or separate buttons. With one click the entire table could be exported, rather than needing to export a page at a time and concatenate them.
2) Allow the row count of the table to be increased to at least 100. In this situation the export of only visible rows would still export enough players to still be useful in this case. Performance would need to be considered.

Currently I am exporting the first page to Excel, and then exporting subsequent pages to clipboard, and pasting them into the Excel sheet.

**Comment by halkeye** [comment]
While technically a duplicate, I like your write up way more than https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/224

Do you have any interest in attempting it? Its pretty easy to generate a CSV, and I don't think any server has thousands of players.

**Comment by saminal1** [comment]
Oh, I did look through the issues for a pre existing one! Damn.

Yes interested in trying it, but it's a big stretch from where my skills are currently. I'll have a look when I've got time to get stuck into it and see.

**Comment by halkeye** [comment]
So currently it looks like the datatable javascript library shows the table, and provides the pdf and xslx buttons 
https://datatables.net/reference/button/pdf

based on https://datatables.net/faqs/index#Server-side-processing it doesn't look like it can be done out of the box

It depends on what cata says, but personally, I would remove all 4 buttons (Copy, PDF, Excel, and Print) and just add one new one that does CSV/Excel. 

* Printing can be done easily enough by printing a csv. Or we could eventually add back in a new media=print css sheet (we might be able to steal from datatables). I doubt its used though, so can be removed and figured out when people complain
* PDF Doesn't really work as its cut off
* Copy, I can't really think of what you'd want that for, but I think I could re-implement that if asked, or we could re-enable it.

That just leaves CSV. Its a pretty standard export format, can be imported into any spreadsheet, super easy to create. 
If we wanted excel, its not hard to convert any code that creates a csv to use https://github.com/SheetJS/sheetjs which is what datatables uses.

Thats a lot of information. 

If you want to start implementing it
* Disable buttons - Removing lines from the templates
* Add new button - simple html `ex <button>Export</button>` plus some javascript

**Comment by saminal1** [comment]
I'll give it a go. Additonally - when exporting to CSV i think the playtime should be rendered as seconds, not hh:mm:ss. I'll have a fiddle and cry for help if I hit a brick wall.

**Comment by niekcandaele** [comment]
Hey, this has been added and will be in the next CSMM release ;)
