### ISSUE TITLE
Add lint-staged to the project

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#435]
Currently we use Husky to run the linter pre-commit but there's some problems with that. Right now it'll lint unstaged content on commit, so can fail, or worse, pass when local is fixed but not added

We should add [lint-staged](https://www.npmjs.com/package/lint-staged)

**Comment by anusha5695** [comment]
@niekcandaele  I can pick this

**Comment by niekcandaele** [comment]
Assigned! Thanks :)
