### ISSUE TITLE
Custom Discord Notification

### ISSUE THREAD

**Issue by PauloAlmas** [CatalysmsServerManager/7-days-to-die-server-manager#448]
Custom Discord Notification could be personalized output, something small like "Player AAAA connected" and not all that stuff.

I wanted output like this 1 text line only per notification:
Next Blood moon in 4 days
Server Rebooting in 5 minutes
Server Up
...

**Comment by niekcandaele** [comment]
So essentially this request is about filtering the output of a custom Discord command into something smaller.

The change would probably happen somewhere here:
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/customHooks/index.js


I'm not sure what the best approach for this would be. Allow users to submit a regex and the notification only outputs what is matched by the regex perhaps? Open to other ideas

**Comment by PauloAlmas** [comment]
The idea is to get the value of the day bloodmoon, and present the Discord in a single line, instead of that square that appears now ...

Now appears like this:
![image](https://user-images.githubusercontent.com/13030899/97887938-755c2a00-1d22-11eb-8849-1cc4c9349124.png)

And i wanted like this in discord :
Next Blood moon in 4 days

Is this correct:
![image](https://user-images.githubusercontent.com/13030899/97888081-a0467e00-1d22-11eb-8262-fffc8c82960f.png)

![image](https://user-images.githubusercontent.com/13030899/97888093-a3da0500-1d22-11eb-95ee-e2e4973b4cad.png)

**Comment by PauloAlmas** [comment]
yes, or disbled notification and show only output 🔢

**Comment by saminal1** [comment]
Hi @PauloAlmas

Cata has now added a sendDiscord() function which can be used with an automation job or hook to send a simple message, rather than the current embed. Documentation is available at https://docs.csmm.app/en/CSMM/functions.html#senddiscord-channel-message

**Comment by niekcandaele** [comment]
I'll close this now, saminal has answered this question. Can reopen if this is still an issue
