### ISSUE TITLE
Discord Bot Name

### ISSUE THREAD

**Issue by PauloAlmas** [CatalysmsServerManager/7-days-to-die-server-manager#452]
ingame server : bloodmoon is in 2 days
ingame server : nighttime 2h

1 player writes in discord chanel text AAAAAAA
ingame DiscordRobo  : AAAAAAA

i just whant diferent names ingame for discord bridge and server messages

whether it's saying announcements, or discord messages, or cron jobs

**Comment by niekcandaele** [comment]
I did not 100% get what you are asking but I am pretty sure it is a duplicate of #214 . I'll close this issue in favour of the other one
