### ISSUE TITLE
Launch Errors

### ISSUE THREAD

**Issue by Chrisnetika** [CatalysmsServerManager/7-days-to-die-server-manager#46]
1st time setting this up on a fresh debian 9 vm with all the requirements, fully the setup guide fully as per
https://docs.csmm.app/en/csmm/self-host/installation.html#configuring-csmm
https://imgur.com/1mZr1Ch
https://i.imgur.com/P8DI1BU.png

**Comment by niekcandaele** [comment]
What version of MySQL are you using? In older versions, the key length is limited to 767 bytes.

See https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes for more info

**Comment by Chrisnetika** [comment]
believe it was using MariaDB, i trashed the instanced and instead went with ubuntu 18.04 base and did the installation guide again and it works now.
Some reason Debian 9.4 an issue

**Comment by niekcandaele** [comment]
Debian is not the issue, it was a mismatch in database versions. MariaDB is **very** close to MySQL but not fully the same.
