### ISSUE TITLE
CustomCommands that include a ; get split at places they shouldn't be

### ISSUE THREAD

**Issue by niekcandaele** [CatalysmsServerManager/7-days-to-die-server-manager#468]
Consider the following command: `command1;command2;command3 "aaa;bbb"`

This will result in execution of
- command1
- command2
- command3 "aaa
- bbb"

This is not ideal. [The helper currently takes an array of strings](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/helpers/sdtd/execute-custom-cmd.js#L15). I propose this is changed to allow a string to be passed in and let the helper be responsible for splitting the commands properly. This will allow handling the quoted semicolon properly.

When changing this, any current usage of that helper will need to be adjusted as well. Eg the [`split()` call here](https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/worker/processors/hooks/index.js#L66) should be removed and just pass the full string. CTRL+f'ing for `sails.helpers.sdtd.executeCustomCmd` should reveal all the places that need adjusting.

**Comment by saminal1** [comment]
would this cause a problem with the section under 
// Check if the command matches any custom functions
      let customFunction = checkForCustomFunction(commandToExec);
??

i.e. if the array isn't split before sending, any custom fuctions in the second or subsequent spots will be ignored and sent straight to the sdtd server?

**Comment by saminal1** [comment]
i suppose you could split the array, check each part for custom functions, and then if none are found send the original string rather than the split array to the helper?

**Comment by niekcandaele** [comment]
Would need to account for that yes! Likely will need some refactors to support this.

I don't think there's proper tests for this helper, if we fix this issue, we should at least some basic assertions to make sure the function works correctly

**Comment by halkeye** [comment]
https://stackabuse.com/regex-splitting-by-character-unless-in-quotes/

I'm certain there's packages or scripts out there that will do it, it's common enough problem

**Comment by niekcandaele** [comment]
Aha indeed!

https://www.npmjs.com/package/split-string

:)
