### ISSUE TITLE
Players Ranks / Rolls

### ISSUE THREAD

**Issue by PauloAlmas** [CatalysmsServerManager/7-days-to-die-server-manager#534]
Could be a good addon in chant see players rolls or make new table with ranks like player with most kills on server would be called Killer... and or like militaty ranks, player level X rank Y, all similiar to rolls but with auto update maybe 1x day ...
![image](https://user-images.githubusercontent.com/13030899/106352373-70cfef00-62da-11eb-8a9c-260f1e3c9de7.png)

**Comment by saminal1** [comment]
Hi @PauloAlmas 

With the new handlebars system that Cata has implemented, I think this is now possible with an automation hook. Are you in the discord? If so we can discuss how to set this up there.

Cheers
Sam (saminal in discord)

**Comment by niekcandaele** [comment]
This is possible with the Handlebars system, closing this issue :)
