### ISSUE TITLE
Teleportation Saves

### ISSUE THREAD

**Issue by Shadow39R** [CatalysmsServerManager/7-days-to-die-server-manager#570]
**Is your feature request related to a problem? Please describe.**
The teleportation feature is very... empty.

**Describe the solution you'd like**
Allow us to bookmark spots. Check screenshot.

**Describe alternatives you've considered**
Rat does this feature nicely.

**Additional context**
Rat
![image](https://user-images.githubusercontent.com/80421234/110683225-a3e68780-8190-11eb-9b1e-8bb414515af7.png)
CSMM
![image](https://user-images.githubusercontent.com/80421234/110683499-f32cb800-8190-11eb-9de9-934cc12375e3.png)

**Comment by niekcandaele** [comment]
That's a really good feature!
