### ISSUE TITLE
Make item suggestions case insensitive

### ISSUE THREAD

**Issue by Shadow39R** [CatalysmsServerManager/7-days-to-die-server-manager#571]
**Is your feature request related to a problem? Please describe.**
The Give Items feature is bugged or needing adjustment

**Describe the solution you'd like**
The feature is case sensitive thus makes us undesirable. 

**Describe alternatives you've considered**
1) Remove case sensitive
2) Disallow the option to spawn "Master" items as such can crash the game.

**Additional context**
Rat
![image](https://user-images.githubusercontent.com/80421234/110684002-7948fe80-8191-11eb-8feb-606505cf2d33.png)
Lowercase "orb" = no desired results 
![image](https://user-images.githubusercontent.com/80421234/110684172-adbcba80-8191-11eb-8963-fc6ae1f886a0.png)
Uppercase "Orb" = Desired results
![image](https://user-images.githubusercontent.com/80421234/110684252-c6c56b80-8191-11eb-90e2-9e9d0cd078f3.png)

**Comment by niekcandaele** [comment]
Agree on the case sensitivity!

Can you elaborate on `Disallow the option to spawn "Master" items as such can crash the game.`?

**Comment by Shadow39R** [comment]
Excuse my lack of coding language, I hope I make sense.
In the XML, we have things called Master. These are items that have no real value, no icon, no anything. They are items that are not meant to spawn in the actual game but give other items values. 
![image](https://user-images.githubusercontent.com/80421234/110686110-e1004900-8193-11eb-83f3-7deb5bd80bdd.png)
For example, instead of having the same code written for 3 items, I just write one Master item and have the others "extend" from it with their unique values.
As such in the example, OrbMaster has all the desired values.
Copper, Silver, and Gold Orbs just extend and have a different icon tint and description. 

Master Items should not spawn and can cause server crashes.

**Comment by niekcandaele** [comment]
Aha I understand! So what would be a good fix?

We could filter the items for the word "Master" but that seems very fragile. Is there a solid way to check if an item can/should be spawned?

**Comment by halkeye** [comment]
could also add a per server config (list of item names) to prevent showing up in the suggestion/spawning? A blocklist or something? then let the server admin manage the list themselves

**Comment by Shadow39R** [comment]
I think Rat scans the Localization.txt to get Items instead of the items.xml. This forced Admins to make sure custom items have a Localization.txt if they want them spawned.

**Comment by niekcandaele** [comment]
Hmm, that would mean a breaking change. I'd rather not force people to have to modify their modded item configs. 

I've made a PR for the case sensitivity, that's going to close this issue. It'll be included in the next update

 Please feel free to create a new issue about the master items though!
