### ISSUE TITLE
Tolerate CPM commands in JSON Imports

### ISSUE THREAD

**Issue by sjellema** [CatalysmsServerManager/7-days-to-die-server-manager#706]
Currently CSMM will reject the import of any export that contains CPM commands such as "say2" and "shutdownba" (unrecognized commands).

With the close relationship between the two projects it should be tolerated at import.

**Comment by niekcandaele** [comment]
What import is this?
Can you provide a JSON file to reproduce this please?

**Comment by sjellema** [comment]
Here is one example, but if any export contains say2 or shutdownba (and presumably any non-CSMM native command) it is rejected at the time of import because it contains bad commands.  So what I’ve been doing is a search-replace to use “say” and “shutdown” so I can get it imported, then I manually go back to edit in the “say2” and “shutdownba” where appropriate.

**Comment by niekcandaele** [comment]
I think your attachment got lost when you replied via mail? :)
