### ISSUE TITLE
Enhancing the Dashboard

### ISSUE THREAD

**Issue by Shadow39R** [CatalysmsServerManager/7-days-to-die-server-manager#810]
Ideas to enhance the Dashboard.

1. PLAYER ACTION MENU AT A GLANCE
This will allow us to just selet the players and apply the actions on the go.
![image](https://user-images.githubusercontent.com/80421234/128963835-7dc1a612-ea9f-407f-920f-f3a9106cbc05.png)

2. A BETTER BALANCE
This will allow admins to send currency on the go rather than having to pull out a calculator and adding the total as the current system forces us to.
![image](https://user-images.githubusercontent.com/80421234/128963846-557dd4c2-4229-4c37-9389-5328922cfd7f.png)

3. AUTOFILLING COMMANDS
This will release the necessity of memorizing commands. This system will help you enter the variables.
![image](https://user-images.githubusercontent.com/80421234/128963856-fb77600e-a1c4-4f86-8c18-e3363026273e.png)

**Comment by niekcandaele** [comment]
I really like these suggestions! Thank you, definitely on the roadmap

**Comment by niekcandaele** [comment]
I've split this into several different issues and added more info on how to intergrate them :)

https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/884
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/883
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/885
