### ISSUE TITLE
Pull CpmDonorSlots.xml Contents into CSMM

### ISSUE THREAD

**Issue by forbiddenwon** [CatalysmsServerManager/7-days-to-die-server-manager#851]
check to see if the DS file is avail, and if it is:

1)
would it be possible to pull the contents of CpmDonorSlots.xml into CSMM?

would be very helpful to see in CSMM when assigning roles, if a player DS is set up, and also when cleaning up roles from expired DS players.

would like this content to be seen in both the individual player profile and the player overview/export page

2)
i know that CSMM doesnt interact directly with the server files, and uses the API.... having the above would be great to help maintain.... ill go that one step further, requesting, IF csmm were able to send the DS add/remove commands too, would be awesome
If the DS file exists, show info in each player profile
then give ability to remove the date via CSMM,  (issue the ds remove)
also give ability to change the date (issue the ds remove, then the ds add)
adding the dates from today to make the new date, vs trying to figure out if the existing date is more or less, figuring the math on the difference, then issuing a +/- days command.

**Comment by niekcandaele** [comment]
While I understand this feature request, I'm afraid this will not make it into CSMM.

Both me and Prisma do not want CSMM and CPM to be tightly coupled. Both projects should remain independent.
