### ISSUE TITLE
Adding "Sort" toggle to roles column in player overview screen 

### ISSUE THREAD

**Issue by TheBaptizer** [CatalysmsServerManager/7-days-to-die-server-manager#87]
Are you able to look at adding a "sort" toggle on the roles column in the player overview screen, Alternatively or also add the provision to download *all* player data to excel for filtering.

Thank you.

**Comment by niekcandaele** [comment]
This is some Datatables configuration to be done

The role field is explictily set to not be orderable, unsure why though 
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/views/sdtdServer/players.ejs#L102

Possibly related to this file as well
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/controllers/SdtdServer/get-players-datatable.js

**Comment by svaller** [comment]
Sorting on roles would be super useful.  I was doing player maintenance today in an attempt to clean up the roles.  We are finding that the player's roles are not downgrading automatically so we are having to do it by hand.  And, searching through thousands of players to find people with roles sucks.

We have the players link their discord to CSMM and then when we upgrade their role that works.  But, when we downgrade their role it stays at the elevated role.  We then have to go in by hand and change their role.  This sorting would make the job a heck of a lot easier.

**Comment by niekcandaele** [comment]
Hey, this has been added and will be in the next CSMM release ;)

**Comment by niekcandaele** [comment]
And re the exporting, was fixed in this issue: https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/434
