### ISSUE TITLE
Clear out failed/cleaned queue after a while

### ISSUE THREAD

**Issue by halkeye** [CatalysmsServerManager/7-days-to-die-server-manager#94]
We don't need a billion past jobs

halkeyeToday at 3:50 PM
https://github.com/OptimalBits/bull/issues/854 <-- probably worth cleaning queues once in a while
GitHub
Set the failed/completed jobs automatically removed after a period ...
Hi all, Do we have an option in Bull allows to remove the failed/completed jobs in queue after a period time (1 day/week/month)? I think it&#39;s necessary because it can reduce the number item...

☕ CatalysmToday at 3:51 PM
Yeah good catch
That first comment looks like a decent workaround for now
halkeyeToday at 3:53 PM
yea

**Comment by niekcandaele** [comment]
Queues are now capped at last 100 jobs for both completed and failed status.
