### ISSUE TITLE
Question for discord

### ISSUE THREAD

**Issue by CRYINGFOROU** [CatalysmsServerManager/7-days-to-die-server-manager#980]
could we mabe get a channel for advertising one's server so people can find new servers and good ones on the discord, cuz i see alot of people writing on discord for help and i'm intrested in trying their server's but idk how to find them

**Comment by niekcandaele** [comment]
Hi there, thanks for your suggestion! We've discussed this internally and have decided that this is not something we want to add to the CSMM Discord server. We want to keep the focus on CSMM and related projects.
